export const LOAD_PRODUCTS="LOAD_PRODUCTS"
export const GET_ALL_PRODUCTS_SUCCESS="GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_FAIL="GET_ALL_PRODUCTS_FAIL"

export const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL="ADD_PRODUCT_FAIL"

export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL"

export const EDIT_PRODUCT_SUCCESS=" EDIT_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_FAIL="EDIT_PRODUCT_FAIL"

export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL="GET_PRODUCT_FAIL"